### ISSUE TITLE
Share ssh known_hosts with the container

### ISSUE THREAD

**Issue by B-Galati** [composer/docker#10]
Hello,

Is there any technique to share the ssh known_hosts file with the container ?

Like :

```bash
docker run --rm --interactive --tty \
    --volume $PWD:/app \
    --volume $SSH_AUTH_SOCK:/ssh-auth.sock \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --volume $PWD/.ssh:/composer/.ssh \
    --user $(id -u):$(id -g) \
    --env SSH_AUTH_SOCK=/ssh-auth.sock \
    composer install
```

It looks like SSH keeps setting .ssh to the container user home even if home env variable is set.

**Comment by B-Galati** [comment]
I found a solution. 

I added this line in my dockerfile :

```
RUN echo "UserKnownHostsFile /home/user/.ssh/known_hosts" >> /etc/ssh/ssh_config
```

Any though ?

Perhaps it would be a good idea to add this line to composer Dockerfile ?

**Comment by alcohol** [comment]
```
--volume local/path/to/known_hosts:/etc/ssh/ssh_known_hosts
```

This has no place in the base image however.

**Comment by B-Galati** [comment]
Thanks for the feedback ! I tried this solution but it was not working for some reason. I should have missed something. I will try it again. Thanks for the feedback :)
