### ISSUE TITLE
Error message `curl_multi_setopt(): CURLPIPE_HTTP1 is no longer supported ` with latest docker container

### ISSUE THREAD

**Issue by johanv** [composer/docker#100]
Hi,

I use the composer docker container in a .gitlab-ci file [for a hobby project](https://gitlab.com/rva-vzw/dikdikdik) I'm working on, so that I can run automatic tests everytime I push new code to my repository. Whichs usually works great; thank you for providing this container image!

Now for a week or something, running `composer install` with your container started to fail. I got this error message:
```
24 $ composer install
25                                                               
26   [ErrorException]                                            
27   curl_multi_setopt(): CURLPIPE_HTTP1 is no longer supported  
28                                                               
32 ERROR: Job failed: exit code 1
```
(see also e.g. [this job log](https://gitlab.com/rva-vzw/dikdikdik/-/jobs/370037883) on gitlab)

I was using the 1.8-version of your container (I suppose this is now 1.8.6), so I tried the latest one (1.9.1), but that also didn't work. But when [I tried using version 1.9.0 of your container](https://gitlab.com/rva-vzw/dikdikdik/merge_requests/29/diffs?commit_id=6fa3cc59045cbd4cd6ce1571ba89c0880b831871), the pipeline passed.

So probably I'm doing something wrong, or maybe there is a bug in version 1.9.1 and 1.8.6 of your container.

Anyway, I decided to post this issue, so in case someone else is having the same problem, google will at least find something.

**Comment by alcohol** [comment]
This is part of Symfony flex. If you run in verbose mode you will see the stack trace. See https://github.com/symfony/flex/issues/515

**Comment by diamondlee** [comment]
Wondering why this issues is closed and https://github.com/symfony/flex/issues/515 is also closed. one of these should be open so this issues can be fixed asap.

**Comment by alcohol** [comment]
It is fixed, but probably not in the version of Flex that you have installed locally.
There is nothing to do here in this repository though, hence why I closed this issue.

**Comment by diamondlee** [comment]
odd i am using symfony/flex 1.5.3 which is latest. so again i am wondering when this will be fixed
![image](https://user-images.githubusercontent.com/4379628/70451656-5fd77500-1a6b-11ea-9659-c300bad14e28.png)

**Comment by alcohol** [comment]
Okay, but this is not the place for that. /unsubscribed
