### ISSUE TITLE
Tagging strategy

### ISSUE THREAD

**Issue by nick-zh** [composer/docker#101]
Hey

I am thinking if it would maybe nice to have a more specific tagging strategy.
Since right now images are based on 7-alpine, it means, it was automatically updated from `php:7.3` to `php:7.4`.
It seems configuring extensions (like gd), is done differently now in `php:7.4`. If you are using composer to install dependencies, this can lead to inconsistencies in your Dockerfiles, if you are using something below `php:7.4` in your other images. I am interested what your thoughts are on that.
Thanks in advance for taking the time.

Cheers,
Nick

**Comment by alcohol** [comment]
The readme on the Docker hub accurately describes how to use this image (don't extend it, use multistage builds).
