### ISSUE TITLE
Consider adding a new build for multi stage

### ISSUE THREAD

**Issue by exussum12** [composer/docker#105]
With a multi stage build (as suggested in the read me), the use case really copy a single file to a new container.

To do this currently you need to download the following

```
d95b3f498002        11 days ago         /bin/sh -c #(nop)  CMD ["composer"]             0B                  
<missing>           11 days ago         /bin/sh -c #(nop)  ENTRYPOINT ["/bin/sh" "/d…   0B                  
<missing>           11 days ago         /bin/sh -c #(nop) WORKDIR /app                  0B                  
<missing>           11 days ago         /bin/sh -c #(nop) COPY file:098af1c9d6ed00c2…   1.13kB              
<missing>           11 days ago         /bin/sh -c set -eux;   curl --silent --fail …   1.94MB              
<missing>           11 days ago         /bin/sh -c #(nop)  ENV COMPOSER_VERSION=1.9.3   0B                  
<missing>           11 days ago         /bin/sh -c #(nop)  ENV COMPOSER_HOME=/tmp       0B                  
<missing>           11 days ago         /bin/sh -c #(nop)  ENV COMPOSER_ALLOW_SUPERU…   0B                  
<missing>           11 days ago         /bin/sh -c printf "# composer php cli ini se…   66B                 
<missing>           11 days ago         /bin/sh -c set -eux;   apk add --no-cache --…   678kB               
<missing>           11 days ago         /bin/sh -c set -eux;   apk add --no-cache --…   95.1MB              
<missing>           11 days ago         /bin/sh -c #(nop)  CMD ["php" "-a"]             0B                  
<missing>           11 days ago         /bin/sh -c #(nop)  ENTRYPOINT ["docker-php-e…   0B                  
<missing>           11 days ago         /bin/sh -c docker-php-ext-enable sodium         171kB               
<missing>           11 days ago         /bin/sh -c #(nop) COPY multi:0b7e4a1b9cd5748…   6.53kB              
<missing>           11 days ago         /bin/sh -c set -eux;  apk add --no-cache --v…   64.6MB              
<missing>           11 days ago         /bin/sh -c #(nop) COPY file:ce57c04b70896f77…   587B                
<missing>           11 days ago         /bin/sh -c set -eux;   apk add --no-cache --…   10.3MB              
<missing>           11 days ago         /bin/sh -c #(nop)  ENV PHP_SHA256=cf1f856d87…   0B                  
<missing>           11 days ago         /bin/sh -c #(nop)  ENV PHP_URL=https://www.p…   0B                  
<missing>           11 days ago         /bin/sh -c #(nop)  ENV PHP_VERSION=7.4.3        0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV GPG_KEYS=42670A7FE4D0…   0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV PHP_LDFLAGS=-Wl,-O1 -…   0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV PHP_CPPFLAGS=-fstack-…   0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV PHP_CFLAGS=-fstack-pr…   0B                  
<missing>           6 weeks ago         /bin/sh -c set -eux;  mkdir -p "$PHP_INI_DIR…   0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV PHP_INI_DIR=/usr/loca…   0B                  
<missing>           6 weeks ago         /bin/sh -c set -eux;  addgroup -g 82 -S www-…   4.68kB              
<missing>           6 weeks ago         /bin/sh -c apk add --no-cache   ca-certifica…   2.79MB              
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV PHPIZE_DEPS=autoconf …   0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop) ADD file:e69d441d729412d24…   5.59MB  
```

Which is roughly 180MB.

The file we are interested in in 1.9MB.

Im happy to do thr work here just trying to see if it its wanted / useful to make a new image as follows
```
FROM scratch
COPY --from=composer:latest /usr/local/composer /usr/local/composer
```

This would then be a new image maybe composer-file ? so people interested in the multi stage build would then do 

```
COPY --from=composer-file /usr/bin/composer /usr/bin/composer
```

Download ~2MB and have the same functionality

**Comment by alcohol** [comment]
Honestly I am not sure what the added value of this is. @tianon do you see any value here?

**Comment by tianon** [comment]
I agree, this seems strange -- it's an image that's not intended to be run at all, but only intended for distribution of a single file?  What makes that different from just downloading https://getcomposer.org/download/1.10.9/composer.phar (with or without verifying the SHA from https://getcomposer.org/download/)?

**Comment by exussum12** [comment]
Not sure how common a use case this is, but I have multiple PHP projects, each one of them would then need to download the script using wget (seems more common than curl, alpines base image has wget for example). doable, but not cache effective as this cant be shared between images.

Currently this is shared between images, so 180mb downloaded shared across x images isnt too bad. This pattern is called "optimal" in the docs and is used fairly frequently on github and I imagine more in closed source applications
https://github.com/search?q=%22COPY+--from%3Dcomposer+%2Fusr%2Fbin%2Fcomposer%22&type=Code

also " We do not provide a Composer image for each supported PHP version because we do not want to encourage using Composer as a base image or a production image."

Just providing the file would achieve that, ill look at adding a bare minimum PHP to the container too so composer can work

**Comment by alcohol** [comment]
While I understand your point of view, I would argue that there is also a relatively large chance that those layers are already cached locally since the majority of users build their production images by extending from the PHP alpine base images (just like us). Of course, I understand that this is not always the case.

I am just not sure that offering a `-bin` flavor of each tagged release makes much sense in the context of the official images library. If these 180mb are that important to you, you could always create your own base image containing only the binary by extending our official image in the way you described in your opening post and using that to distribute the binary across your other images.

**Comment by exussum12** [comment]
Closing the issue
