### ISSUE TITLE
SIGSEV on arm32 v6

### ISSUE THREAD

**Issue by StefanSchoof** [composer/docker#117]
I try to build an docker image for arm32 v6 for [volkszaehler.org](https://github.com/volkszaehler/volkszaehler.org).
Using the composer:1 image on a raspberry pi zero w with raspbian I run
```shell
git clone https://github.com/volkszaehler/volkszaehler.org.git --depth 1
cd volkszaehler.org
docker build --no-cache .
```
And get the error
`The command '/bin/sh -c composer install --no-ansi --no-scripts --no-dev --no-interaction --no-progress --optimize-autoloader' returned a non-zero code: 139`

Running composer direct on the raspbian all is working. Running the docker build on arm32 v7 (raspberry pi 3) and on x64 it works without problems.

Running a cross build on x64 does not produce this error, but I looks like the command does not ever complete (I cancelled after about 1 hour)

**Comment by andig** [comment]
> Running composer direct on the raspbian all is working. Running the docker build on arm32 v7 (raspberry pi 3) and on x64 it works without problems.

There is only an arm/v6 image- should that work on the pi zero?

**Comment by StefanSchoof** [comment]
I am unsure what you mean.

The docker image of composer has an arm v6 and v7 image:
![Screenshot_20200809-155805](https://user-images.githubusercontent.com/4662023/89733950-46068b80-da59-11ea-984a-877a57dec69a.png)

The rpi1 and zero are arm v6 all other have an arm v7 cpu.

So the arm v6 image should work (like the alpine arm v6 does) on the rpi zero.

An other interested point is that 
```
docker run composer:1 help
```
does work on the zero. Looks like the memory error only occur in the install part.
