### ISSUE TITLE
Add php5.6 as supported image

### ISSUE THREAD

**Issue by hnk** [composer/docker#12]
I would love to use this image, but we are still stuck on php5.6.
Could you add support for that through the php:5.6-alpine docker image?

**Comment by alcohol** [comment]
I don't understand, what does the PHP version of this image have to do with your application?

**Comment by hnk** [comment]
I am sorry if I misunderstood an error I saw during our deployment testing. I'll explain the error now and post a excerpt from the logs once I'm back at the office tomorrow.

We wanted to use this image during our deployment phase in gitlab ci. So we'd use it as part of our build chain during deployment.

Sadly during the CI run composer complains that the installed php version (7.1) that composer uses is not compatible with the dependencies it is trying to install (php version 5.6).

**Comment by alcohol** [comment]
Not necessarily. You might just have to set the target platform version in your `composer.json` (this is recommended for projects, not libraries). See https://getcomposer.org/doc/06-config.md#platform for more information.

**Comment by hnk** [comment]
Thank you, this was exactly the right solution!

Sorry for keeping you busy :disappointed_relieved: But know that you saved my day!
