### ISSUE TITLE
composer home directory not writable when running as custom user

### ISSUE THREAD

**Issue by alcohol** [composer/docker#13]
When running the Composer image as follows

```
docker run --rm \
  --volume /etc/passwd:/etc/passwd:ro \
  --volume /etc/group:/etc/group:ro \
  --user $(id -u):$(id -g) \
  composer install
```

the default `COMPOSER_HOME` (`/composer`) cannot be written to by the user which is used to run the process. Since these Containers are ephemeral and single-run only, I am not sure if having a writable cache is of any use. Regardless, it would be nice to avoid having Composer throw warnings around.

**Comment by meteorlxy** [comment]
Maybe we can use something like `--volume ~/.composer/cache:/composer/cache:rw` to enable the cache?

**Comment by alcohol** [comment]
I defaulted the `COMPOSER_HOME` to `/tmp` in the image template. The next release should see this change. So in future release (`> 1.4.2`) you can do `--volume ~/.composer/cache:/tmp/cache:rw`.

**Comment by meteorlxy** [comment]
I see. BTW, is there a way to change the default packagist source globally? I have to make a new image adding `RUN composer config -g repo.packagist composer https://custom.packagist.source `

**Comment by alcohol** [comment]
Your solution is the only way to make it an explicit default in the image/container itself.

Alternatively, you can mount your `~/.composer` directory into `/tmp` inside the image (assuming the composer configuration on your host has this desired default changed).

**Comment by bicpi** [comment]
This change is not yet reflected in the docs.

**Comment by alcohol** [comment]
It should be soon. https://github.com/docker-library/docs/pull/981
