### ISSUE TITLE
No composer.json present in the current directory

### ISSUE THREAD

**Issue by vivek-sculptsoft** [composer/docker#142]
Hello,

While installing packages as per my existing implementation, with latest composer image, I am getting following error..

![image](https://user-images.githubusercontent.com/25892485/97530328-e1aff400-19d7-11eb-8978-58f3598e08f1.png)

With downgrading the 1.9.3, all worked fine.

Can anyone please check and help us?

**Comment by alcohol** [comment]
Can you provide some more details? E.g. your environment (host details), what your `composer.json` contains, and what the output looks like when you specify very verbose output (`-vvv`).

**Comment by lewisvgd** [comment]
Issue can be closed - prestissimo is composer 1.0 only and composer:latest is now composer 2.0
