### ISSUE TITLE
missing ext-exif * into docker image 

### ISSUE THREAD

**Issue by cp-vrkansagara** [composer/docker#153]
Root composer.json requires PHP extension ext-exif * but it is missing from your system. Install or enable PHP's exif extension.

**Comment by alcohol** [comment]
You should not rely on the php version in our container. There are several ways work around this.

- You can use `--ignore-platform-reqs`: https://getcomposer.org/doc/03-cli.md#install-i

	```
	composer install --ignore-platform-reqs
	```

- You can specify the target platform in your `composer.json` if you know it will not change often: https://getcomposer.org/doc/06-config.md#platform

	```
	{
		"require": { ... },
		"config": { "platform": { "php": "7.1.3" } }
	}
	```

- You can use composer in your own Docker image if you have one by using multi-stage builds: https://docs.docker.com/develop/develop-images/multistage-build/

	```
	COPY --from=composer:1 /usr/bin/composer /usr/bin/composer
	```

**Comment by cp-vrkansagara** [comment]
@alcohol  this is not a solution , you have to provide a way that How a user can install using this docker layer.

**Comment by alcohol** [comment]
[Documentation](https://hub.docker.com/_/composer) is already available. I suggest you take the time to read it. Also, a small suggestion, try to refrain from telling people what they have to do or not do.

**Comment by cp-vrkansagara** [comment]
@alcohol  If you can able to provide a small code this is really helpful to me and others as well.
