### ISSUE TITLE
Old images moved to PHP 8 ?

### ISSUE THREAD

**Issue by partikule** [composer/docker#162]
It is possible to get back one image with PHP 7 ?

PHP 8 breaks Symfony projects .

**Comment by alcohol** [comment]
See #161

**Comment by partikule** [comment]
I used the version 2.0.7 and it is fine.

I read the #161.
You said : " it is clearly documented that you should not rely on the php version of our image".
I agree, this is true and documented.

Btw, on some projetcs (Symfony or Laravel for example) , the fact is that the version of PHP has an impact (in our case, it brokes the CI/CD process)
I'm totally OK that the "lastest" Composer image continuously follow the last tech.
But...
What was very surprising is that a lot of "old" images where also updated to PHP 8.
In my mind, that means that :
-  Old and stable PHP project (like our's, not currently migrated to PHP8) can be impacted because one "old" Composer package has be upgraded 
- Developers should not consider Docker Composer packages as "stable" (that's curious...)
- "I made the PR for upgrading to PHP 8 because I worked on this version for a while" looks like a "Young developer approach", with non consideration for real life usages (without any offence ! :-) )

I thank you for your answer.
I hope you understand our point.

**Comment by alcohol** [comment]
If you rely on a specific PHP version and certain extensions, we highly encourage you use your own custom image in your CI/CD pipelines.

E.g., even though my demo project generally follows the latest versions wherever possible, I still have a custom `Dockerfile` for local development: https://github.com/alcohol/pastebin-php/blob/1f2c2180eed9676a0390a1f61d30038a3e12c4f2/docker/fpm/Dockerfile#L48-L54

**Comment by partikule** [comment]
Ok, I will follow your advice.

Btw, if the 2.0.8 stays at PHP 7 and will stay stable, it is just fine !

**Comment by alcohol** [comment]
Older tags do not get overwritten, except when you use `composer/composer` instead of `composer` as your image.
