### ISSUE TITLE
How to use with PHP < 8 ?

### ISSUE THREAD

**Issue by phpguru** [composer/docker#166]
I am running into this situation:

My composer.json has:
```
    "require": {
        "php": "^7.2.5",
        ...
     }
```

I have this in ~/.bashrc running under WSL2 Ubuntu 20
```
alias composer="docker run -it --rm -u $UID -v `pwd`:/app composer"
alias php="docker run -it --rm -u $UID -v `pwd`:/app php:7.4 `which php`"
```

When I cd to ~/myproject and `composer install` I get:
```
me@laptop ~/projects/sites/website (master)$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires php ^7.2.5 but your php version (8.0.2) does not satisfy that requirement.
```

Can we make a PHP 7.4, and maybe even a PHP 5.6 Dockerized composer?

**Comment by phpguru** [comment]
I have made this 
https://github.com/phpguru/docker-php-composer/tree/php7.4
and this
https://github.com/phpguru/docker-php-composer/tree/php5.6

I'd be happy to create PRs into similar branches on your repository, or I can include in different folders if you prefer that.

I tested these with `docker build -t composer:7.4 .` and `docker build -t composer:5.6 .` respectively; then aliasing composer to the specific tagged version.

**Comment by alcohol** [comment]
https://github.com/docker-library/docs/tree/master/composer#php-version--extensions

**Comment by phpguru** [comment]
Thanks for the link!
