### ISSUE TITLE
hub.docker.com has not been triggered

### ISSUE THREAD

**Issue by raszi** [composer/docker#175]
Please trigger a docker build to include the security fix introduced in `2.0.13`.

**Comment by raszi** [comment]
It would be also a good idea to set up an automatic build process for this project on `hub.docker.com`.

**Comment by alcohol** [comment]
Not sure what you mean?

The community maintained images ([`composer/composer`](https://hub.docker.com/r/composer/composer)) are updated through Github actions, see: https://github.com/composer/docker/actions/runs/791691940

The official images ([`composer`](https://hub.docker.com/_/composer)) are pending PR: https://github.com/docker-library/official-images

Docker hub builds are not used.

**Comment by raszi** [comment]
Well, I got confused then since the tag links on the https://hub.docker.com/_/composer page point to here.

**Comment by alcohol** [comment]
Yes. But official images cannot be uploaded directly. They have to be approved and processes through the proper channels. So while this repository is the source for the official image (and our vendor image), new tags will not appear on Docker hub until the above mentioned PR is merged.

**Comment by raszi** [comment]
Thank you for the clarification and sorry for the unnecessary issue.

**Comment by alcohol** [comment]
No problem at all. Happy to clarify. I'm definitely interested in trying to automate more of this process, as long as the whole workflow remains transparant and easy to understand for contributors and the community in general :-)

**Comment by alcohol** [comment]
Updated the README of this repository to include a description of the release workflow(s) for now.

**Comment by raszi** [comment]
Thank you for the extra effort!
