### ISSUE TITLE
Use with others containers and host

### ISSUE THREAD

**Issue by webmasterpf** [composer/docker#176]
Hello,

How can I use this container to provide composer to others ?
I have a PHP container which actually use compose v1.10 and I would to update composer via this container instead of to do so in the PHP one.

Other point, I would to use this composer container to provide the composer command to the host. 

Is it possible ? (both points)
How can I do that ? (both points)

Thanks

**Comment by alcohol** [comment]
> How can I use this container to provide composer to others ?

Use multistage builds and copy the binary from our official image to your image / specific stage. See for example:

https://github.com/alcohol/pastebin-php/blob/3953635ae2bc1998b1814269b7f97773fda4765a/docker/fpm/Dockerfile#L49-L56

---

> Other point, I would to use this composer container to provide the composer command to the host.

There are several ways to do this. I personally use the following wrapper script:

Note: for this to work, `$HOME/bin` should be part of your `$PATH`.
```sh
$ cat ~/bin/composer
```
```sh
#!/usr/bin/env bash

set -euo pipefail

if ! command -v docker >/dev/null 2>&1; then
  echo "Cannot run 'composer', Docker not available" >&2
  exit 1
fi

tty=
tty -s && tty=--tty

docker run \
  $tty \
  --interactive \
  --rm \
  --env COMPOSER_HOME \
  --env COMPOSER_CACHE_DIR \
  --user $(id -u):$(id -g) \
  --cap-drop ALL \
  --read-only \
  --tmpfs /tmp \
  --volume $COMPOSER_HOME:$COMPOSER_HOME:delegated \
  --volume $COMPOSER_CACHE_DIR:$COMPOSER_CACHE_DIR:delegated \
  --volume /etc/passwd:/etc/passwd:ro \
  --volume /etc/group:/etc/group:ro \
  --volume "$(pwd)":/workdir \
  --workdir /workdir \
  composer "$@"
```

**Comment by webmasterpf** [comment]
Thanks.
So I'm new to docker, I've never use a dockerfile, only a docker-compose.  Do I need to add it ?

**Comment by alcohol** [comment]
I am sorry, but I do not have enough spare time to give you an introduction into Docker / Docker-Compose. I recommend you read their documentation, it is quite excellent.
