### ISSUE TITLE
Docker images updated to PHP 8 and breaks our composer container

### ISSUE THREAD

**Issue by oranges13** [composer/docker#177]
We have been using `composer:1.10.20` in our docker files for a while, but recently it updated to PHP 8 (why were old tags updated?) and now breaks our installations.

We have added the 
```
"config": {
    "platform": {
        "php": "7.4.0"
     }
}
```
into our composer.json file but it still says that it's trying to use PHP 8.0.3

Please advise.

**Comment by simonhammes** [comment]
This is just a guess: 
Did you commit the composer.lock file in your project? If yes, Composer will install the dependencies listed in the lock file. Afaik you have to run `composer update --lock` for the changes to take effect

**Comment by alcohol** [comment]
You should not rely on the php version in our container. There are several ways work around this.

- You can use `--ignore-platform-reqs`: https://getcomposer.org/doc/03-cli.md#install-i

	```
	composer install --ignore-platform-reqs
	```

- You can specify the target platform in your `composer.json` if you know it will not change often: https://getcomposer.org/doc/06-config.md#platform

	```
	{
		"require": { ... },
		"config": { "platform": { "php": "7.1.3" } }
	}
	```

- You can use composer in your own Docker image if you have one by using multi-stage builds: https://docs.docker.com/develop/develop-images/multistage-build/

	```
	COPY --from=composer:1 /usr/bin/composer /usr/bin/composer
	```
