### ISSUE TITLE
Problem mounting volume

### ISSUE THREAD

**Issue by lucraraujo** [composer/docker#187]
When I run the command
```
docker run --rm --interactive --tty \
  --env COMPOSER_HOME \
  --env COMPOSER_CACHE_DIR \
  --volume ${COMPOSER_HOME:-$HOME/.config/composer}:$COMPOSER_HOME \
  --volume ${COMPOSER_CACHE_DIR:-$HOME/.cache/composer}:$COMPOSER_CACHE_DIR \
  --volume $PWD:/app \
  composer install
```
I get the error:  `docker: Error response from daemon: invalid volume specification: '/home/lucas/.config/composer:'.`

Image: composer:latest
Versions:
Docker: 20.10.7
PHP: 8.0.7
Composer: 2.1.3

**Comment by alcohol** [comment]
Looks like you don't have a value for `$COMPOSER_HOME`.
