### ISSUE TITLE
Publish Docker images to ECR Public 

### ISSUE THREAD

**Issue by gitnik** [composer/docker#192]
Following the introduction of rate limits on the Docker Hub (https://docs.docker.com/docker-hub/download-rate-limit/), AWS has released a public version of ECR, called ECR Public (https://aws.amazon.com/blogs/aws/amazon-ecr-public-a-new-public-container-registry/).

Given the rate limit on the Docker Hub it would great to see composer publish its packages to ECR Public as well. 

Right now people are already [uploading composer images to ECR Public themselves](https://gallery.ecr.aws/?searchTerm=composer&page=1) but having an official account publish them would obviously be preferred from a security perspective.

**Comment by alcohol** [comment]
Fine with me. But I'm on vacation this week.

**Comment by gitnik** [comment]
> We are part of the Docker open source program which makes our downloads unlimited

We're definitely seeing composer images go towards our quota. 

Appreciate the openness and looking forward to this being implemented eventually :)

**Comment by alcohol** [comment]
The official image should not count towards rate limits. The `composer/composer` image however will count towards rate limits since we have not applied for an open source exemption on said vendor image.

**Comment by Seldaek** [comment]
I thought we did for the whole composer org? But who knows, I have close to no idea how their stuff works. Anyway we'll work on getting this to AWS ECR.

**Comment by alcohol** [comment]
I just ran some basic tests and it doesn't look like the official image nor the vendor image are exempted from rate-limits. It is unclear to me if we qualified for anything yet or not. Did you not get an email a while ago?

**Comment by Seldaek** [comment]
Yes they said this a month ago:

> We have whitelisted your namespace "composer" and this should come into effect in the next week or so. With this whitelisting, the Docker data pull rate policies that went into effect last November, will not apply to the users pulling images from your namespace.  

I asked again to confirm.

**Comment by alcohol** [comment]
The community workflow now automatically publishes to our Amazon Public ECR. Unfortunately getting it verified (so it looks more official) is quite another story and possibly out of reach for now.

**Comment by Seldaek** [comment]
Had to cut through some red tape nonsense but I finally got them to verify the repo so now we have a logo and ✔️ 
 and a sensible URL: https://gallery.ecr.aws/composer/composer 🥳

**Comment by alcohol** [comment]
Do I need to modify the push target?

**Comment by Seldaek** [comment]
I think it's just an alias on their end so should be fine as is.

**Comment by gitnik** [comment]
Thanks a lot guys :)
