### ISSUE TITLE
Document global install changes since 1.4.2

### ISSUE THREAD

**Issue by r4j4h** [composer/docker#21]
# Problem

Composer default global path changed in Docker image tag 1.4.3 without documentation, causing any dependencies on the default global path to break.

# Verification through Config

Note that 1.4.2 uses `/composer` while newer images use `/tmp`.

```
$> docker run composer:1.4.2 composer config --list --global | grep dir
[vendor-dir] vendor (/app/vendor)
[bin-dir] {$vendor-dir}/bin (/app/vendor/bin)
[cache-dir] /composer/cache
[data-dir] /composer
[cache-files-dir] {$cache-dir}/files (/composer/cache/files)
[cache-repo-dir] {$cache-dir}/repo (/composer/cache/repo)
[cache-vcs-dir] {$cache-dir}/vcs (/composer/cache/vcs)
[archive-dir] .
$> docker run composer:1.4.3 composer config --list --global | grep dir
[vendor-dir] vendor (/app/vendor)
[bin-dir] {$vendor-dir}/bin (/app/vendor/bin)
[cache-dir] /tmp/cache
[data-dir] /tmp
[cache-files-dir] {$cache-dir}/files (/tmp/cache/files)
[cache-repo-dir] {$cache-dir}/repo (/tmp/cache/repo)
[cache-vcs-dir] {$cache-dir}/vcs (/tmp/cache/vcs)
[archive-dir] .
$> docker run composer:latest composer config --list --global | grep dir
[vendor-dir] vendor (/app/vendor)
[bin-dir] {$vendor-dir}/bin (/app/vendor/bin)
[cache-dir] /tmp/cache
[data-dir] /tmp
[cache-files-dir] {$cache-dir}/files (/tmp/cache/files)
[cache-repo-dir] {$cache-dir}/repo (/tmp/cache/repo)
[cache-vcs-dir] {$cache-dir}/vcs (/tmp/cache/vcs)
[archive-dir] .
```

# Reproduction steps (1/2):

Look for the `Changed current directory to <x>` lines.

1.4.2:
```
$> docker run composer:1.4.2 composer global require --dev jakub-onderka/php-parallel-lint
Changed current directory to /composer
Using version ^0.9.2 for jakub-onderka/php-parallel-lint
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing jakub-onderka/php-parallel-lint (v0.9.2): Downloading (100%)         
jakub-onderka/php-parallel-lint suggests installing jakub-onderka/php-console-highlighter (Highlight syntax in code snippet)
Writing lock file
Generating autoload files
```

1.4.3:

```
$> docker run composer:1.4.3 composer global require --dev jakub-onderka/php-parallel-lint
Changed current directory to /tmp
Using version ^0.9.2 for jakub-onderka/php-parallel-lint
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing jakub-onderka/php-parallel-lint (v0.9.2): Downloading (100%)         
jakub-onderka/php-parallel-lint suggests installing jakub-onderka/php-console-highlighter (Highlight syntax in code snippet)
Writing lock file
Generating autoload files
```

Latest:

```
$> docker run composer composer global require --dev jakub-onderka/php-parallel-lint
Changed current directory to /tmp
Using version ^0.9.2 for jakub-onderka/php-parallel-lint
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing jakub-onderka/php-parallel-lint (v0.9.2): Downloading (100%)         
jakub-onderka/php-parallel-lint suggests installing jakub-onderka/php-console-highlighter (Highlight syntax in code snippet)
Writing lock file
Generating autoload files
```

# Reproduction steps (2/2):

Folders affected by command above:

```
$> docker diff <container-id>
C /composer
C /composer/cache
A /composer/cache/<snipped>
A /composer/cache/repo
A /composer/cache/repo/<snipped>
A /composer/composer.json
A /composer/composer.lock
A /composer/vendor
A /composer/vendor/autoload.php
A /composer/vendor/bin
A /composer/vendor/bin/parallel-lint
A /composer/vendor/composer
A /composer/vendor/composer/<snipped>
A /composer/vendor/jakub-onderka
A /composer/vendor/jakub-onderka/php-parallel-lint
A /composer/vendor/jakub-onderka/php-parallel-lint/<snipped>
C /root
A /root/.subversion
A /root/.subversion/<snipped>
C /tmp
```

Folders affected by command in 1.4.3:

```
$> docker diff <container-id>
C /root
A /root/.subversion
A /root/.subversion/<snipped>
C /tmp
C /tmp/cache
A /tmp/cache/<snipped>
A /tmp/cache/repo
A /tmp/cache/repo/<snipped>
A /tmp/composer.json
A /tmp/composer.lock
A /tmp/vendor
A /tmp/vendor/autoload.php
A /tmp/vendor/bin
A /tmp/vendor/bin/parallel-lint
A /tmp/vendor/composer
A /tmp/vendor/composer/<snipped>
A /tmp/vendor/jakub-onderka
A /tmp/vendor/jakub-onderka/php-parallel-lint
A /tmp/vendor/jakub-onderka/php-parallel-lint/<snipped>
```

Folders affected by command in latest:

```
$> docker diff <container-id>
C /root
C /tmp
C /tmp/cache
Jasmines-iMac:cluster-creation-tool jhegman$ docker diff 792
C /root
A /root/.subversion
A /root/.subversion/<snipped>
C /tmp
C /tmp/cache
A /tmp/cache/<snipped>
A /tmp/cache/repo
A /tmp/cache/repo/<snipped>
A /tmp/composer.json
A /tmp/composer.lock
A /tmp/vendor
A /tmp/vendor/autoload.php
A /tmp/vendor/bin
A /tmp/vendor/bin/parallel-lint
A /tmp/vendor/composer
A /tmp/vendor/composer/<snipped>
A /tmp/vendor/jakub-onderka
A /tmp/vendor/jakub-onderka/php-parallel-lint
A /tmp/vendor/jakub-onderka/php-parallel-lint/<snipped>
```

# Suggested Fix

Some documentation might be nice or the presence of this issue may help others debug if they have any problems.

**Comment by alcohol** [comment]
I think you mean that the default home directory changed?

This change should only impact a very small subset of users. I am sorry for the inconvenience it might have caused you though. You are indeed correct that the current documentation is not up to date. I will remedy this tomorrow.

**Comment by r4j4h** [comment]
Yes, in so fewer words. 😊 

Thank you for the prompt consideration!

**Comment by alcohol** [comment]
The docs should now be up to date. If you anything to add, please let me know.
Otherwise, can we consider this issue resolved?

**Comment by gamelaster** [comment]
Eh, sorry for writing to closed issue, but I didn't anything about this in documentation. I had working script in docker (Gitlab CI probably selected the latest version of container):
```
composer global require justinwalsh/daux.io
daux --source=docs --destination=public
```
Latest successful build has been 4th August 2017, after that, I getting `daux: command not found`.
I fixed it by `export PATH=$PATH:/tmp/vendor/bin/`, but I think it will be good to export PATH automatically.

**Comment by alcohol** [comment]
I am missing sufficient context to understand how your issue is related exactly.

**Comment by gamelaster** [comment]
@alcohol In older versions of container (probably 1.4.2), the `PATH` environment variable contains composer's global bin directory. After changing global path (1.4.3+), the `PATH` doesn't contains valid path to composer's global bin directory, so I can't launch for sample `daux` command without adding path to `PATH` environment variable.

**Comment by alcohol** [comment]
That is highly unlikely, as we never set the PATH environment variable to anything specifically, and the default PATH does not include the composer global bin directory. Are you using our image directly? Or have you extended it using your own Dockerfile?

**Comment by alcohol** [comment]
I am sorry, I just double checked and I stand corrected. In older versions we did use `ENV PATH "/composer/vendor/bin:$PATH"`. We stopped doing this because global installs inside a container make no sense anyway.

The Composer container should be considered a throw-away tool. You run it against a volume bind and then destroy it once it has completed its task. If you really need to set the PATH and such, you can do so yourself.

We removed most defaults because preferably our Container leaves as much as possible up to the end user to decide. We merely set the absolute minimum required to run the Container hassle free.
