### ISSUE TITLE
Command `show --platform` gives different results because PHP version is different?

### ISSUE THREAD

**Issue by woutersamaey** [composer/docker#220]
I wanted to use this docker image to get a list of all requirements in my project, specifically which PHP modules were to be used.
When I use this image to get this list using command

```
docker run --rm --interactive --volume /path/to/my/project:/app --user 1000:1000 composer:2 show --platform --no-ansi
```

It shows a different list then when I run `composer show --platform --no-ansi` on my host machine (running PHP 7.4)

Does this mean I need to make my own image? Or is there an easier option?

**Comment by alcohol** [comment]
`show --platform` lists extensions/modules loaded by the current interpreter. This can be different for containers vs. host.
