### ISSUE TITLE
Private repository installed from - dirty - cache

### ISSUE THREAD

**Issue by armetiz** [composer/docker#23]
Hi there,

I'm trying to install a private repository; but I'm encountering a problem with "cache" that I do not understand.

From two different Docker for mac hosts, mine & one of my teammate.

```bash
docker run --rm --interactive --tty \
     --volume $PWD:/app \
     --volume ~/.ssh:/root/.ssh:ro \
     composer:1.5.1 install
```

> Installing dependencies (including require-dev) from lock file
> Package operations: 1 install, 0 updates, 0 removals
>   - Installing acme/event-store (dev-master eca84f8): Cloning eca84f8625 from cache

The above is common on both environment.
On my computer, the library was correctly installed but on the other the library was not installed... Only the `.git` has been created.

I've tried to `clear-cache`

```bash
docker run --rm --interactive --tty \
     --volume $PWD:/app \
     --volume ~/.ssh:/root/.ssh:ro \
     composer:1.5.1 clearcache
```

But; every time that I'm running composer install, this library, and only this one is installed from cache. But, what cache ?

**Comment by alcohol** [comment]
Please provide a reproducible scenario (composer.json) and full verbose output (-vvv).
