### ISSUE TITLE
No files on the host

### ISSUE THREAD

**Issue by aruku** [composer/docker#238]
I've tried to use this image to create a SF app but there are no files in my project afterward.
I can see all the output as expected, but nothing gets written to disk, at least not in the directory I'm in.

Tried also with just a `composer init` and same result.

I'm using the command indicated in the README:
```
docker run --rm --interactive --tty \
  --volume $PWD:/app \
  composer init
```

I'm on Windows.

What am I missing?

**Comment by alcohol** [comment]
This is just an assumption, but I am guessing that the environment variable `$PWD` might not be available on Windows. I do not use Windows myself, but I am certain there are Google results out there that can guide you to the appropriate alternative for Windows.

**Comment by alcohol** [comment]
https://www.google.com/search?q=pwd+environment+variable+on+windows seems to yield results that could guide you

**Comment by aruku** [comment]
That is a good suggestion, although I've installed Git for Windows and I have a binary for `pwd` on the path:
```
edun6@MSI-GLARUKU65 MINGW64 ~
$ pwd
/c/Users/edun6
```
Where is `pwd` used? I searched the Dockerfile and the two sh files for the 2.2 and 2.3 directories and I couldn't find it.

**Comment by alcohol** [comment]
It's used when mounting the volume when you run the container (at least, in the given example above).

```shell
docker run --rm --interactive --tty \
  --volume $PWD:/app \ # here we tell docker to mount the current working directory to /app inside the container
  composer init
```

It could be that on windows, it is case sensitive. Can you check if `$pwd` and `$PWD` both yield the same value?

**Comment by aruku** [comment]
Oh, right. Damn, I'm asleep. @_@

I think I found the culprit:
```
edun6@MSI-GLARUKU65 MINGW64 ~
$ docker run --interactive --tty   --volume $PWD:/app composer
docker: Error response from daemon: mkdir C:\Users\edun6;C: Access is denied.
See 'docker run --help'.
edun6@MSI-GLARUKU65 MINGW64 ~
$ pwd
/c/Users/edun6
```
Notice the extra _;C_ being added when using `$PWD` in the command.
I'll just indicate the full path. Thank you for your help!
