### ISSUE TITLE
Errors due to missing ext-gd

### ISSUE THREAD

**Issue by maxxwv** [composer/docker#239]
I'm having issues recently with the latest version of Docker Composer where I have to use `--ignore-platform-req=ext-gd` on every composer install. The GD library is a standard install insofar as I understand it; is there a reason why it's apparently not installed on this image? Or am I just missing something?

**Comment by alcohol** [comment]
You should not rely on the php version or extensions in our container. There are several ways to work around this.

- You can use composer in your own Docker image if you have one by using multi-stage builds: https://docs.docker.com/develop/develop-images/multistage-build/

	```
	COPY --from=composer:1 /usr/bin/composer /usr/bin/composer
	```

- You can use `--ignore-platform-reqs`: https://getcomposer.org/doc/03-cli.md#install-i

	```
	composer install --ignore-platform-reqs
	```

- You can specify the target platform in your `composer.json` if you know it will not change often: https://getcomposer.org/doc/06-config.md#platform

	```
	{
		"require": { ... },
		"config": { "platform": { "php": "7.1.3" } }
	}
	```
