### ISSUE TITLE
Possibility to add own ca certificates

### ISSUE THREAD

**Issue by t3easy** [composer/docker#24]
To replace php+composer with docker and this image on local dev machines you write up a nice example:
```
composer () {
    tty=
    tty -s && tty=--tty
    docker run \
        $tty \
        --interactive \
        --rm \
        --user $(id -u):$(id -g) \
        --volume /etc/passwd:/etc/passwd:ro \
        --volume /etc/group:/etc/group:ro \
        --volume $(pwd):/app \
        composer "$@"
}
```
the only problem we have is that we can't add our own ca certificate on runtime.
A possible solution could be mounting a folder with the certs `-v ~/Documents/ca-certificates:/usr/local/share/ca-certificates:ro` and run `update-ca-certificates > /dev/null 2>&1` from the docker-entrypoint.sh

**Comment by alcohol** [comment]
Such a specific use-case should be solved with a personal/custom container though. The official image is not meant to facilitate very specific use-cases. It is as slim/lean and minimalistic as possible.

**Comment by t3easy** [comment]
Having self hosted vcs like gitlab with certificates from an internal CA is not a specific use-case I guess.

**Comment by alcohol** [comment]
We tailor to the majority. Your use-case simply is not that. So yes, it is considered specific. You are entitled of course to disagree :-)

**Comment by t3easy** [comment]
OK, so maybe add a note to the doc, that it is not possible to receive composer packages  from servers with internal CAs with this image.

**Comment by alcohol** [comment]
There is no need to document every specific use-case that is *not* possible with this container. Users encountering such issues tend to have the knowledge / know-how to resolve those themselves.
