### ISSUE TITLE
 [BC] COMPOSER_HOME=/tmp breaks BC

### ISSUE THREAD

**Issue by dkarlovi** [composer/docker#25]
I've wrapped this image and am using it as a base for [my CI/QA type image](https://github.com/dkarlovi/php-toolbox).

What started happening is our build took way longer than before, I didn't pay much attention but it was pointed out to me it downloads all packages every time, clearly a cache issue.

It came down to the image introducing (or changing?) `COMPOSER_HOME` env variable which now points to `/tmp`, but used to point to `/composer`. Seeing it's probably irrelevant for the image itself where it points to, the path could have stayed the same here.

[I've since fixed it](https://github.com/dkarlovi/php-toolbox/commit/3e78510a167a69cf95d32071d1b9ad016d62c260), but it would make sense to default to previously hardcoded values if not significant enough, like this one?

**Comment by alcohol** [comment]
It is not irrelevant, there were issues with the previous path.

**Comment by dkarlovi** [comment]
@alcohol can you be a bit more specific, I'm looking through the commits and can't find anything relevant.

**Comment by dkarlovi** [comment]
I'm guessing you mean https://github.com/composer/docker/issues/13. Makes sense, it's unfortunate this failed without any warning or anything.

Closing, thanks.

**Comment by alcohol** [comment]
I can understand this was an inconvenient change.

I believe we should add some thorough documentation regarding how to use Composer in CI/CD flows. While our image makes it very simple to quickly run Composer anywhere, doing it properly actually would lean more towards creating your own image and making use of the new multistage options Docker now offers. See #22 also.

**Comment by dkarlovi** [comment]
Might consider emitting a warning if the container can see the cache folder is not inside a mount point?

**Comment by alcohol** [comment]
That is not desirable, since generally there is no need to have the cache folder inside of a mount point.

**Comment by dkarlovi** [comment]
I'm talking from within the container. For a container, mount point = volume.

Meaning: if you know `$COMPOSER_ROOT/cache` doesn't resolve to a mounted volume, you're writing cache inside the container which basically means you're not using cache at all, as the container's lifespan is one command run long.

**Comment by alcohol** [comment]
Yes, and since this is the default behaviour, we are not going to throw warnings about this.

**Comment by dkarlovi** [comment]
If Composer's default behaviour is not to use cache, not throwing warnings about not using cache from this image seems reasonable, didn't know it was the default.

**Comment by alcohol** [comment]
You are confusing Composer's default behaviour and the default use-case this image is build for. They are entirely separate things.

The default use-case for this image is single-run throw-away commands.

**Comment by dkarlovi** [comment]
It might be crystal clear to a maintainer, but to a average user this image might be interpreted like "Composer in a box", in which case Composer (and its behaviour/defaults/etc) is the product, Docker image is just the delivery method. This point goes further by the fact the image version is exactly equal to the Composer version it's packaging.

I'd expect the image to behave exactly like Composer itself does, but that's my opinion, you're the one putting in the work. :+1: Nvm then, thanks for your time.

**Comment by alcohol** [comment]
I think that the average user understands how Docker works. Also, this is where documentation already provides enough information.

https://github.com/docker-library/docs/blob/00def8bd8d5fc4a83f001dc46324e9c85a230343/composer/content.md#L19-L26
