### ISSUE TITLE
Using alpine as default

### ISSUE THREAD

**Issue by Webysther** [composer/docker#26]
Is more secure to add suffix `-alpine` for docker optimized for this dist. My suggest is change tag to exists the normal version and the alpine version as PHP, Node and a bunch of official images.

**Comment by alcohol** [comment]
There is no need for that. Our official image is aimed at quick throw-away commands. If you need an image that supports exactly your target environment, you should create that image, and simply copy Composer from our image into yours, using the (relatively new) multistage build approach.

**Comment by Webysther** [comment]
I don't really need a image to target environment, just ask to keep the same pattern to create tag like other projects.

**Comment by alcohol** [comment]
Sure, if we actually offered multiple flavours that would make sense and I would agree.
But we do not offer that. So there is no need for additional tagging.
