### ISSUE TITLE
Composer scripts are not executed

### ISSUE THREAD

**Issue by back-2-95** [composer/docker#27]
For example if I have custom script in composer.json:

```
"scripts": {
        "do-magic": [
            "@composer install",
            "rm -rf cache && mkdir -m 777 cache",
            "symlink something somewhere",
        ],
...
```

So running `docker run --rm -t -v $(pwd):/app composer do-magic` gives:

```
/docker-entrypoint.sh: line 60: exec: serve: not found
```

**Comment by alcohol** [comment]
Your error does not correlate to your example. Also, to run a specific script, it should be:

```
docker run --rm --tty -v $(pwd):/app composer run-script do-magic
```

**Comment by alcohol** [comment]
You cannot use the "shortcut" version because of the way the docker-entrypoint works.

**Comment by back-2-95** [comment]
Yes that works. Is "the way the docker-entrypoint works" in this image or generally in Docker images?

**Comment by alcohol** [comment]
You can look at it ([`docker-entrypoint.sh`](https://github.com/composer/docker/blob/master/docker-entrypoint.sh)). It is a quite common approach. It provides a good mix between supporting running the intended application as conveniently as possible, while also still making it possible to run other binaries without having to override the ENTRYPOINT or CMD through command line arguments.

Unfortunately, we need to use a hardcoded list of composer commands to differentiate between whether a user wants to run a composer command or another binary inside the container. This means the "shortcut" (it's more of a last-resort attempt to help users who make mistakes) where composer will try to resolve a non-existent command through the scripts section does not work.
