### ISSUE TITLE
I want to use php8.1

### ISSUE THREAD

**Issue by sotato-abe** [composer/docker#271]
I was originally using php8.1 on my project, but now php has been updated and I am getting errors.
Is there any way to specify php8.1?

**Comment by sotato-abe** [comment]
I also tried using the "--ignore-platform-reqs" option, but it is stuck on another error.

**Comment by alcohol** [comment]
I need more context to understand what your problem is. I also recommend reading https://github.com/docker-library/docs/tree/master/composer#troubleshooting

**Comment by sotato-abe** [comment]
Resolved.
Thank you very much.
