### ISSUE TITLE
[Question/Feature Request] Provide minor tag image versions on community repository

### ISSUE THREAD

**Issue by jnoordsij** [composer/docker#274]
Hey there 👋

First of all thanks for making these images. I've been using the official images for a while now, and recently stumbled upon the new `bin` version introduced here. I know these aren't published as official images (and probably won't be anytime soon due to the official images policy), so I considered switching to the community version.

However, I noticed that there are no minor-specific tags (e.g. `2.5`) on the community DockerHub, only major specific (e.g. `2`) and patch specific (e.g. `2.5.1`) tags. For the official images, these tags actually do exist. I do somewhat prefer to keep the minor version tagged, to have more or less fuctionally stable builds across different environments, while not requiring regular manual updates. 

Is this intentional, or just the way it was built and open for contributions/PR's to add these to the list of tags?

**Comment by alcohol** [comment]
> Is this intentional, or just the way it was built and open for contributions/PR's to add these to the list of tags?

Probably "the way it was built". The official image has these aliases through the manifest we create using the [generate-stackbrew-library.sh](https://github.com/composer/docker/blob/main/generate-stackbrew-library.sh) script. These tags could be added to the non official image jobs. I can pick it up when I have time, or you can submit a PR and I'll be happy to merge it for you.
