### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by eknowlton** [composer/docker#29]
I have been trying to use composer to install a application but I have dependencies that require php ^5.5.9|>=7.0.8.

Is there a way to upgrade the version of php? Or a different possible solution that i'm not aware of?

**Comment by alcohol** [comment]
I can think of two options right off the bat:
1. You can pass `--ignore-platform-reqs` during `install` or `update`.
2. You can emulate your target platform using the [`platform`](https://getcomposer.org/doc/06-config.md#platform) configuration attribute.

**Comment by hottehead** [comment]
Can we somehow link the php-container and the composer container? So composer could verify the php dependencies which are really installed in the target machine instead of faking a platform config.

**Comment by alcohol** [comment]
No, but you could just build your own composer container by extending from your base php container and using multi-stage builds:


_./Dockerfile_:
```
FROM my-base-php-container
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
```

```
docker build -t composer:custom .
```

And then just use this `composer:custom` image to do all your dependency installing etc.

**Comment by hottehead** [comment]
Thanks, I choose this way to build my images. I now tag those images with _build_ and use them in the CI pipeline. Simplified and reduced the size of my production images =)
