### ISSUE TITLE
Documentation incorrect for multi-stage builds

### ISSUE THREAD

**Issue by benfreke** [composer/docker#290]
Hi

https://hub.docker.com/r/composer/composer is incorrect. It states that a multistage build command for the bin images should look like this: 

```
COPY --from=composer/composer /usr/bin/composer /usr/bin/composer
```

It should instead look like this:

```
COPY --from=composer/composer /composer /usr/bin/composer
```

I don't believe that the instructions are a file in this repo or I would have submitted a PR for it. 

I'm sure I'm not the only one who would have missed this. 
You can see the correct path in Docker Hub here: https://hub.docker.com/layers/composer/composer/latest-bin/images/sha256-a6a518709735610ef3ca249db8b8941e185fad472a3ec06eaab6038e185ab43f?context=explore 

I believe this may be due to the original copy of the "official" composer image, where `/usr/bin/composer` is the correct path.

**Comment by alcohol** [comment]
You are correct. I have updated the documentation of the community image (through Docker hub).
