### ISSUE TITLE
Bitbucket Private Repository

### ISSUE THREAD

**Issue by dylansm** [composer/docker#31]
I'm trying to use a private repository hosted on Bitbucket and I can't get it to work using either auth.json or COMPOSER_AUTH environment variable. Either way I get a permission denied (publickey) error.

I'm following the directions here: https://getcomposer.org/doc/05-repositories.md#bitbucket-driver-configuration

I can confirm that I have a env variable COMPOSER_AUTH in my container and it looks like:

```
COMPOSER_AUTH={
  "bitbucket-oauth": {
    "bitbucket.org": {
      "consumer-key": "my-key",
      "consumer-secret": "my-secret"
    }
  }
}
```

Any thoughts on what I could try next? The only luck I've had is when I link my private key as a volume (but I don't want to use that method). Is there something I am missing? Some way to let docker composer know not to use a key but instead use OAuth?

**Comment by dylansm** [comment]
I'm closing this because it works if I properly link auth.json to /tmp/auth.json within container - using uid 1000 without home directory.

**Comment by alcohol** [comment]
`/tmp` is the value `COMPOSER_HOME` directory within the container.

**Comment by ItsReddi** [comment]
Could you please reopen this?
You have solved your problem in another way but the fact that COMPOSER_AUTH env variable does not work is still true

tank you :)
