### ISSUE TITLE
Label `org.opencontainers.image.source`

### ISSUE THREAD

**Issue by ro0NL** [composer/docker#330]
Hi,

See eg. https://github.com/mlocati/docker-php-extension-installer/pull/848

So we get transparent dependency updates in renovate PRs

This could be handled in Dockerfile, or 'label on build' during workflow action, ~or rely on `docker/metadata-action` which also takes care of it.~ (source should point to https://github.com/composer/composer)

**Comment by alcohol** [comment]
I will accept a PR to the relevant Dockerfile's.

**Comment by ro0NL** [comment]
The goal is to get a changelog for https://github.com/composer/composer/compare/2.7.1...2.7.2 yes 

> org.opencontainers.image.source URL to get source code for building the image (string)

'source code' is relative, so IMHO it plays out :) then again, at this point, im not sure how other integrations would behave.

From renovate POV im not sure it can get a changelog for this repo, since there are no tags, nor GH releases here.

Im tempted to just try it :)
