### ISSUE TITLE
Pin to upstream version

### ISSUE THREAD

**Issue by brt-mlaccetti** [composer/docker#37]
PHP 7.2 is the newest `php:7-alpine`, which doesn't support xdebug, so everything went boom.  Maybe be a bit less wide-ranging than just a major number, and pin to a minor as well?

**Comment by alcohol** [comment]
Why? This image does not use xdebug.

**Comment by brt-mlaccetti** [comment]
We use the image as a base for building and testing, which requires xdebug; worked fine when `7-alpine` pulled in 7.1, but sadly is broken with 7.2. Do you have any ideas as to how we could continue to use the composer image (which we love) and still get xdebug to work (without resorting to an alpha)?

**Comment by alcohol** [comment]
I would highly recommend using multi-stage builds if you need a custom image.

So make your base image extend whichever php image you want (could even be a custom one you made yourself), and then simply use this in your `Dockerfile` (docker 17.05 and upwards):

```
COPY --from=composer:1.5.5 /usr/bin/composer /usr/bin/composer
```

**Comment by brt-mlaccetti** [comment]
Great suggestion, thanks.
