### ISSUE TITLE
composer global require - executable file not found in $PATH

### ISSUE THREAD

**Issue by janpapenbrock** [composer/docker#4]
Hey, thanks for putting all the effort into an official image! Well done!

## Working scenario in composer/composer

I'm migrating from `composer/composer:1.1`, where the following Dockerfile worked:

**Dockerfile**
```
FROM composer/composer:1.1

RUN composer global require 'phpmetrics/phpmetrics'

CMD [""]
ENTRYPOINT ["phpmetrics"]
```

**Execution**
```
> docker build --tag phpmetrics . 
...
> docker run --rm phpmetrics --version
PhpMetrics, by Jean-François Lépine (https://twitter.com/Halleck45) version v1.10.0
```
## Not working here

**Dockerfile**

```
FROM composer:1.2.2

RUN composer global require 'phpmetrics/phpmetrics'

CMD [""]
ENTRYPOINT ["phpmetrics"]
```

**Execution**

```
> docker build --tag phpmetrics . 
...
> docker run --rm phpmetrics --version
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"phpmetrics\\\": executable file not found in $PATH\"\n".
```

## Solution, probably

I think it might be made to work with these lines here https://github.com/RobLoach/docker-composer/blob/ac801a0949fa23da7284174d4ab08d76a54148d0/base/Dockerfile#L45-L46

```
ENV PATH /composer/vendor/bin:$PATH
```
**Update:** Apparently, this line is already included in this image, however it appears to not have the desired effect.

## Conclusion

I would expect this to work, and I hope you can include it here.

**Comment by janpapenbrock** [comment]
I don't get what is going on exactly, however some things to note:

1. Output of `composer gloabl require -vvv phpmetrics/phpmetrics` is mostly identical, except for hashes.
2. `VOLUME /composer` vs `VOLUME /app`
3. ```FROM composer:1.2.2

RUN composer global require 'phpmetrics/phpmetrics'
RUN stat /composer/vendor

CMD [""]
ENTRYPOINT ["phpmetrics"]``` gives `stat: can't stat '/composer/vendor': No such file or directory` here, whereas the directory exists when using `composer/composer`

**Comment by alcohol** [comment]
Thank you for reporting this and taking the time to thoroughly investigate the issue.

I am honestly not sure as to what the common conventions are regarding declaring volumes in official base images.

_Perhaps_ it would be best if we did not declare a volume at all.

Please give me the time to get some feedback from some more experienced Docker folks before taking any actions. I will try to get back to you with an answer/solution asap :-)

**Comment by janpapenbrock** [comment]
Thanks for the quick response :) I saw that you explained your line of thought [in the original pull request](https://github.com/docker-library/official-images/pull/2290#issuecomment-259067285) but did not receive feedback on that in particular.

So it's probably best to get some expert knowledge here, happy to wait!

**Comment by alcohol** [comment]
> @yosifkit | alcohol: We usually only declare volumes for things like database storage.

I'll drop the `VOLUME` declaration.

**Comment by alcohol** [comment]
@janpapenbrock the `VOLUME` declaration has been dropped, but it can take a while before the change gets merged. Keep an eye out :-)

**Comment by janpapenbrock** [comment]
Awesome, thank you!

**Comment by janpapenbrock** [comment]
Can confirm that it works as expected now.

**Comment by alcohol** [comment]
Good to hear :-)
