### ISSUE TITLE
Debian version

### ISSUE THREAD

**Issue by lgandras** [composer/docker#45]
Hi,
is there a Debian version planned for this repository? The official docker-library supports it:

https://github.com/docker-library/php/tree/35aedb29009b46af6ea1009c9405d01d3f66968e/7.2

And it comes handy to us, since some packages simply don't run on Alpine

Thank you

**Comment by alcohol** [comment]
No, support for other distros and such is not planned. But you can simply use multi-stage builds to copy the binary from our official images into your custom application container.

In your `Dockerfile`:
```
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
```
