### ISSUE TITLE
composer: The installation directory "/" is not writable

### ISSUE THREAD

**Issue by gabodl15** [composer/docker#46]
I have a problem with laravel, and it is that the route / is local host, in a menu that I have done does not direct me to where I said, but it tells me that the page does not exist, this is in linux mint, because in windows , the same code, exactly the same, if it does its normal function, even when I press the 'home' option it sends me to the local host and not to the 'home' menu, I tried to uninstall and reinstall, and when I'm installing the composer He gave me the message: The installation directory "/" is not writable

I need help

**Comment by alcohol** [comment]
I think you wound up at the wrong repository.

We do not deal with Laravel, menu's or installing/uninstalling anything here.

**Comment by gabodl15** [comment]
I already solved it, first I had to execute sudo su, then su -, and there I wrote the command and executed it normal
