### ISSUE TITLE
Write dependencies to a file

### ISSUE THREAD

**Issue by t3easy** [composer/docker#53]
To use this image in a multistage build, it would be very helpful to write the dependencies to a file.
Than you could copy this file together with `/usr/bin/composer` over to the final build stage and install that packages (in case the final image is alpine based).

**Comment by alcohol** [comment]
Honestly there are not a lot of exotic dependencies required. So I do not quite see the added value of this (nor is it very common practice).

**Comment by t3easy** [comment]
Yes, it's not common, but helpfull to dynamically install dependencies.

**Comment by t3easy** [comment]
If you don't like to write them to a file, what about using something like `RUN apk --no-cache add --virtual .composer-rundeps git subversion openssh mercurial tini bash patch make zip unzip` to create a new virtual package?
Than we could get them during the build by `apk help info --depends -q .composer-rundeps`

**Comment by alcohol** [comment]
I'm fine with that. Please submit a PR.
