### ISSUE TITLE
Add Support for ARM64V8 architecture 

### ISSUE THREAD

**Issue by odidev** [composer/docker#54]
Hi,

The Composer docker package is building and running fine at my end for ARM64v8 architecture.

Branch used to build is: 
````
1.6
````

Please suggest, what needs to be done to raise the request to add support for ARM64v8 arch at official docker library too.

Regards,

**Comment by lag-linaro** [comment]
+1

We have also independently verified this project on ARM64v8.

It would be great to have it `docker pull`able on our platforms.

**Comment by lag-linaro** [comment]
You are a star.  Thank you so much.

**Comment by alcohol** [comment]
I based it purely on the narrowest set of architectures supported by the upstream php-cli-alpine image(s). So it's a little bit of a fingers crossed approach :sweat_smile:

**Comment by alcohol** [comment]
Merged.
