### ISSUE TITLE
Any plan to update to php7.2 and higher?

### ISSUE THREAD

**Issue by yuezh** [composer/docker#64]

**Comment by alcohol** [comment]
```
FROM php:7-alpine3.8
```

So we follow the 7.x branches of upstream automatically. But of course, when they make a new release, we do not automatically also make a new release. 

Regardless, it is not really important as this container is merely provided as a convenience or a base to copy the binary from, and not a run-time container for your production environment or such things.

See
- https://github.com/docker-library/docs/tree/master/composer#suggestions
- https://getcomposer.org/doc/06-config.md#platform
