### ISSUE TITLE
Volume mounting SSH keys not working

### ISSUE THREAD

**Issue by HeathNaylor** [composer/docker#68]
I am attempting to pass in my local SSH private key. To do so I am volume mounting `~/.ssh/id_rsa` into `/root/.ssh/id_rsa`. This is the command I am using:

```
docker run -v `pwd`:/app -v ~/.ssh:/root/.ssh composer install
```

When it gets down to my private repository as described by the `composer.lock` file, I get the following error (private information substituted with filler text):

```
Installing myorg/mypackage (1.0.0): Downloading (failed)    Failed to download myorg/mypackage from dist: The "https://api.gi
thub.com/repos/myorg/mypackage/zipball/<random_hash>" file could not be downloaded (HTTP/1.1 404 Not Found)

Now trying to download from source
  - Installing myorg/mypackage (1.0.0): Cloning <random_hash>

  [RuntimeException]

  Failed to execute git clone --no-checkout 'git@github.com:myorg/mypackage.git' '/app/vendor/myorg/mypackage' && cd '/app/vendor/
myorg/mypackage' && git remote add composer 'git@github.com:myorg/mypackage.git' && git fetch composer
```

**Comment by alcohol** [comment]
did you try running that command manually inside the container by launching a shell instead of composer to see what error git returns?

**Comment by alcohol** [comment]
one of the frequent causes for this kind of error is when the ssh key is owned by a user that the git process cannot recognize (you need to mount /etc/passwd and /etc/group into the container as well - read-only recommended).

**Comment by HeathNaylor** [comment]
I will work on getting directly into the container and seeing permissions today.
