### ISSUE TITLE
Missing keys

### ISSUE THREAD

**Issue by 1ed** [composer/docker#71]
Hello!

Out of the box when I run

```bash
$ docker run -it composer diagnose 
#...
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
#...
```
which is because we rm `COMPOSER_HOME` after install. Why? Thanks!

**Comment by alcohol** [comment]
I don't recall, which probably means there is no reason we do this. Feel free to submit a PR to remedy this.

**Comment by 1ed** [comment]
@alcohol see https://github.com/composer/docker/pull/72
