### ISSUE TITLE
Php automatically updated on the base image

### ISSUE THREAD

**Issue by sergiuionescu** [composer/docker#75]
The base image for the docker composer image is php:7-alpine3.8 which is automatically bumped to the lastest php minor version.
The issue is that a testing step in a CD process might automatically test application code on a newer php minor version.

A potential solution could be to align yourselves to the docker php tagging and publish builds from both 7-alpine3.8 and 7.2-alpine3.8 .

Thanks.

**Comment by alcohol** [comment]
The version of PHP in the Container is irrelevant, see https://getcomposer.org/doc/06-config.md#platform or the `--ignore-platform-reqs` flag for `install`/`update`.
