### ISSUE TITLE
Images with different php version

### ISSUE THREAD

**Issue by Pyton** [composer/docker#81]
Is there any chance to see composer with different versions?
Currently, there is only composer version but would be nice to use composer with different versions.
Why? Cause php version to determine what packages will be installed (if we don't specify lower version than the version in composer package)

**Comment by alcohol** [comment]
No, there is absolutely no need for that. Please read the "suggestions" section here https://hub.docker.com/_/composer

**Comment by alcohol** [comment]
You should not rely on the php version in our container. There are several ways work around this.

- You can use `--ignore-platform-reqs`: https://getcomposer.org/doc/03-cli.md#install-i

	```
	composer install --ignore-platform-reqs
	```

- You can specify the target platform in your `composer.json` if you know it will not change often: https://getcomposer.org/doc/06-config.md#platform

	```
	{
		"require": { ... },
		"config": { "platform": { "php": "7.1.3" } }
	}
	```

- You can use composer in your own Docker image if you have one by using multi-stage builds: https://docs.docker.com/develop/develop-images/multistage-build/

	```
	COPY --from=composer:1 /usr/bin/composer /usr/bin/composer
	```
