### ISSUE TITLE
can't install  repository need Openssl,How Can I install in arm64?

### ISSUE THREAD

**Issue by teddymail** [composer/docker#82]
Downloading (failed)    Failed to download 2amigos/qrcode-library from dist: The "https://files.phpco
mposer.com/files/2amigos/qrcode-library/5356f2355c7ba9a9ced67753411c88c2c095deb0.zip" file could not
be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14004410:SSL routines:CONNECT_CR_SRVR_HELLO:sslv3 alert handshake failure

**Comment by alcohol** [comment]
Wrong repository.

**Comment by alcohol** [comment]
https://github.com/composer/composer
