### ISSUE TITLE
gd support possible?

### ISSUE THREAD

**Issue by MrTB** [composer/docker#86]
Hi, is it possible to include the GD lib support, although I already use --ignore-platform-reqs
by executing composer, one of the Sf script by installation does still check GD, so that the installation failed. Thank you.
--
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception
  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:

  16:02:29 ERROR     [console] Error thrown while running command "--ansi cache:clear --no-warmup". Message: "Gd not installed" ["exception" => Imagine\Exception\RuntimeException { …},"command" => "--ansi cache:clear --no-warmup","mess
  age" => "Gd not installed"]
  In Imagine.php line 172:
    Gd not installed
  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by alcohol** [comment]
Recommend you build your own container in that case :-)
Docker multistage builds are excellent for this as well.

**Comment by MrTB** [comment]
for everybody else that has the same problem:
I just added the parameter:
--no-scripts 
and the problem is solved.
