### ISSUE TITLE
PHP DNS do not work correctly

### ISSUE THREAD

**Issue by Rinma** [composer/docker#88]
Hi,

I have a project that should run the PHPUnit tests in a Pipeline. Therefore I want to use the composer docker container with the tag `1:8`. I also tried to use a PHP container `7.2` and `7.3` and install composer by my self but does not work for me.

Now I have the problem that I use the function `dns_get_record` and when I run the tests it doesn't work correctly.

The project: https://gitlab.com/Rinma/id4me-rp-client-php
The error with composer container: https://gitlab.com/Rinma/id4me-rp-client-php/-/jobs/210377749
The job with PHP container: https://gitlab.com/Rinma/id4me-rp-client-php/-/jobs/210295052

If I run the tests locally or in the PHP container everything works fine.
What am I missing here?

**Comment by alcohol** [comment]
Closing this issue because there has not been any activity on it for a long time.
