### ISSUE TITLE
Why image composer is recent updated ?

### ISSUE THREAD

**Issue by rumours86** [composer/docker#94]
https://hub.docker.com/_/composer?tab=tags
1.8.6 62 MB
Last update: 3 days ago (August 2, 2019 12:44 PM)

It released on Jun 11
https://github.com/composer/composer/releases/tag/1.8.6

And now we have not composer 1.9.0 released this 3 days ago
https://github.com/composer/composer/releases/tag/1.9.0 (Aug 2, 2019, 8:59 PM GMT+2)

Maybe in release script have some error ?

**Comment by alcohol** [comment]
1.9 is pending https://github.com/docker-library/official-images/pull/6411

**Comment by alcohol** [comment]
I do not know what causes the recently updated field to update to the current value. That's a docker hub thing, not something we influence.
