### ISSUE TITLE
Composer could not find a composer.json file in /app

### ISSUE THREAD

**Issue by chawax** [composer/docker#96]
Hi,

I try to run composer Docker container with some code generated from OpenAPI Generator for Slim framework. I work on macOS Mojave.

I run the following command as it is written in the documentation :

```
docker run --rm --interactive --tty --volume $PWD:/app composer install
```

But I have the following error :

```
Composer could not find a composer.json file in /app
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

I can't understand this error since I have a `app` directory with a `composer.json` file under the directory where I run this command from. What am I doing wrong ? Is there a problem with volume mounting ?

Any help welcome :)

**Comment by brettt89** [comment]
Mounting `$PWD` assumes your `composer.json` is in the current directory. If you want to mount your `app/` directory you should change `$PWD` to `app/`.

E.g. 
```
docker run --rm --interactive --tty --volume app/:/app composer install
```

otherwise change directory to your `app/` directory and then run your command.
E.g.

```
cd app/
docker run --rm --interactive --tty --volume $PWD:/app composer install
```

**Comment by chawax** [comment]
Thanks a lot for your help. I could make it work this way :

```
docker run --rm --interactive --tty --volume $PWD/app/:/app composer install
```

**Comment by rsmaximiliano** [comment]
Same error... But I have composer.json in root folder...
project
     composer.json

`cd project`
`docker run --rm --interactive --tty --volume $PWD:/app composer install`

get error

> Composer could not find a composer.json file in /app
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

I use Docker Toolbox in Windows 10 pro

**Comment by alcohol** [comment]
Please keep in mind that not every OS and/or shell has `$PWD` set by default. You can also try using `$(pwd)`.

**Comment by aedork** [comment]
another solution on windows 10 pro is:

```
docker run --rm --interactive --tty --volume ${pwd}:/app composer install
```


> 
> 
> Same error... But I have composer.json in root folder...
> project -> composer.json
> 
> `cd project`
> `docker run --rm --interactive --tty --volume $PWD:/app composer install`
> 
> get error
> 
> > Composer could not find a composer.json file in /app
> > To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
> 
> I use Docker Toolbox in Windows 10 pro

**Comment by Saltibarsciai** [comment]
not working anything above on windows git bash
 1. ls 
 ```
CHANGELOG.md  README.md  app/  artisan*  bootstrap/  composer.json  config/  database/  package.json  phpunit.xml  public/  resources/  routes/  server.php  storage/  tests/  webpack.mix.js
```
running command

```
docker run --rm --interactive --tty --volume pwd:/app composer install
```

getting error 

```
Composer could not find a composer.json file in /app
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage

Fatal error: Uncaught Error: Call to undefined method Composer\Console\Application::areExceptionsCaught() in phar:///usr/bin/composer/src/Composer/Console/Application.php:422
Stack trace:
#0 phar:///usr/bin/composer/src/Composer/Command/BaseCommand.php(63): Composer\Console\Application->getComposer(true, false)
#1 phar:///usr/bin/composer/src/Composer/Command/InstallCommand.php(96): Composer\Command\BaseCommand->getComposer(true, false)
#2 phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\C
onsoleOutput))
#3 phar:///usr/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output
\ConsoleOutput))
#4 phar:///usr/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvI
nput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///usr/bin/composer/src/Composer/Console/Application.php(314): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Con
soleOutput))
#6 phar:///usr/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOut
put))
#7 phar:///usr/bin/composer/src/Composer/Console/Application.php(125): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Conso
leOutput))
#8 phar:///usr/bin/composer/bin/composer(67): Composer\Console\Application->run()
#9 /usr/bin/composer(24): require('phar:///usr/bin...')
#10 {main}
  thrown in phar:///usr/bin/composer/src/Composer/Console/Application.php on line 422
```

and another error if used pwd as `${pwd}`
```
docker: Error response from daemon: OCI runtime create failed: invalid mount {Destination::/app Type:bind Source:/var/lib/docker/volumes/32480d44daf6af6d2ae9b7df43c850504d3209edff31bf4dcf580d1618fcc47d/_data Op
tions:[rbind]}: mount destination :/app not absolute: unknown.
```

**Comment by Blacx** [comment]
> not working anything above on windows git bash
> 
> 1. ls
> 
> ```
> CHANGELOG.md  README.md  app/  artisan*  bootstrap/  composer.json  config/  database/  package.json  phpunit.xml  public/  resources/  routes/  server.php  storage/  tests/  webpack.mix.js
> ```
> 
> running command
> 
> ```
> docker run --rm --interactive --tty --volume pwd:/app composer install
> ```
> 
> getting error
> 
> ```
> Composer could not find a composer.json file in /app
> To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage
> 
> Fatal error: Uncaught Error: Call to undefined method Composer\Console\Application::areExceptionsCaught() in phar:///usr/bin/composer/src/Composer/Console/Application.php:422
> Stack trace:
> #0 phar:///usr/bin/composer/src/Composer/Command/BaseCommand.php(63): Composer\Console\Application->getComposer(true, false)
> #1 phar:///usr/bin/composer/src/Composer/Command/InstallCommand.php(96): Composer\Command\BaseCommand->getComposer(true, false)
> #2 phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\C
> onsoleOutput))
> #3 phar:///usr/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output
> \ConsoleOutput))
> #4 phar:///usr/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvI
> nput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #5 phar:///usr/bin/composer/src/Composer/Console/Application.php(314): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Con
> soleOutput))
> #6 phar:///usr/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOut
> put))
> #7 phar:///usr/bin/composer/src/Composer/Console/Application.php(125): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Conso
> leOutput))
> #8 phar:///usr/bin/composer/bin/composer(67): Composer\Console\Application->run()
> #9 /usr/bin/composer(24): require('phar:///usr/bin...')
> #10 {main}
>   thrown in phar:///usr/bin/composer/src/Composer/Console/Application.php on line 422
> ```
> 
> and another error if used pwd as `${pwd}`
> 
> ```
> docker: Error response from daemon: OCI runtime create failed: invalid mount {Destination::/app Type:bind Source:/var/lib/docker/volumes/32480d44daf6af6d2ae9b7df43c850504d3209edff31bf4dcf580d1618fcc47d/_data Op
> tions:[rbind]}: mount destination :/app not absolute: unknown.
> ```

For windows environment try to escape the path, e.g:
`$ docker run --rm --interactive --tty --volume //d//folder//yourprojectfolder:/app composer install`
