### ISSUE TITLE
Newest version is not tagged "latest"

### ISSUE THREAD

**Issue by fsok** [composer/docker#98]
According to https://getcomposer.org/ the newest version is 1.9.0, but on Docker Hub version 1.8.6 is still tagged as "latest".

**Comment by alcohol** [comment]
You are correct. Forgot to update the aliases in the stackbrew script. Fixed in 0dc15c653059aa6e00b0dfb787f3e05a469c8e68. [PR](https://github.com/docker-library/official-images/pull/6783) submitted.
