### ISSUE TITLE
Composer could not find a composer.json file in /app

### ISSUE THREAD

**Issue by rsmaximiliano** [composer/docker#99]
I run the following command as it is written in the documentation (in my root project, where is a composer.json file):

`docker run --rm --interactive --tty --volume $PWD:/app composer install`

But I have the following error :

> Composer could not find a composer.json file in /app
> To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

Using Windows 10 pro with Docker Toolbox

**Comment by alcohol** [comment]
It is possible that `$PWD` is not defined in your shell. You can try using `$(pwd)` instead of whatever works in your shell for retrieving the current path/working directory (has to be absolute, not relative).

**Comment by yveshema** [comment]
I am having this exact problem. I am at a loss why it is happening. I am trying to install Laravel dependencies, and the command is run inside the project's root, where the composer.json is located. For clarity, this is the command I am running:

`docker run --rm --interactive --tty --volume $(pwd):/app composer install`
Composer could not find a composer.json file in /app
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

Could it be that the `install` command is being run before the volume is established?

**Comment by alcohol** [comment]
What does the following return?

```
echo $(pwd)
docker run --rm --interactive --tty --volume $(pwd):/app composer ls -al
```
